ecs_cluster="rigor_private_location"
region = "us-east-1"
asg_max_instance_count = "1"
asg_min_instance_count = "1"
asg_desired_instance_count = "1"
subnet_id = ""
rigor_agent_key = ""
security_group_id = ""